[[language]]
name = "hcl"
scope = "source.tf"
roots = ["main.tf", ".terraform.d"]
file-types = ["hcl", "tf"]
auto-format = true
language-servers = [ "terraform-lsp" ]
formatter = { command = "tofu" , args = ["fmt", "-"] }

[[language]]
name = "templ"
auto-format = true
scope = "source.templ"
injection-regex = "templ"
grammar = "templ"
file-types = ["templ"]
roots = ["go.sum"]
comment-token = "//"
indent = { tab-width = 4, unit = "\t" }
language-servers = [ "templ" ]
formatter = { command = "templ" , args = ["fmt"] }

[[grammar]]
name = "templ"
source = { git = "https://github.com/vrischmann/tree-sitter-templ", rev = "4519e3ec9ca92754ca25659bb1fd410d5e0f8d88" }

[[language]]
name = "go"
formatter = { command = "goimports" }
# config = { goimports = true, gofumpt = true, staticcheck = true, analyses = { unusedparams = true, unreachable = true } }

[[language]]
name = "nix"
auto-format = true
language-servers = ["nil"]
[language.formatter]
command = "alejandra"

[[language]]
name = "sql"
formatter = { command = "sqlformat", args = ["--reindent", "--indent_width", "2", "--keywords", "upper", "--identifiers", "lower", "-"] }

[[grammar]]
name = "nix"
source = { git = "https://github.com/nix-community/tree-sitter-nix", rev = "1b69cf1fa92366eefbe6863c184e5d2ece5f187d" }

[[language]]
name = "markdown"
file-types = ["md", "eml", "txt"]
language-servers = [ "ltex-ls"]

[[language]]
name = "html"
file-types = ["html"]
auto-format = false
language-servers = ["vscode-html-language-server"]

[[language]]
name = "css"
file-types = ["css", "scss"]
language-servers = ["vscode-css-language-server"] 

[[language]]
name = "javascript"
file-types = ["js"]
language-servers = ["typescript-language-server"]

[language-server."terraform-lsp"]
command = "terraform-lsp"

[language-server.nil]
command = "nil"

[language-server."vscode-html-language-server"]
command = "vscode-html-language-server"
args = ["--add-flags", "--stdio"]

[language-server."vscode-css-language-server"]
command = "vscode-css-language-server"
args = ["--add-flags", "--stdio"] 

[language-server."typescript-language-server"]
command = "typescript-language-server"
args = ["--stdio"]

[language-server."ltex-ls"]
command = "ltex-ls"

[language-server.ltex-ls.config.ltex.dictionary]
"en-US" = ["ewwe","flaberrasted"]
