[[language]]
name = "hcl"
scope = "source.tf"
roots = ["main.tf", ".terraform.d"]
file-types = ["hcl", "tf"]
auto-format = true
formatter = { command = "/home/jcmuller/.asdf/shims/terraform", args = ["fmt", "-"] }
language-server = { command = "terraform-lsp" }
#language-server = { command = "terraform-ls", args = ["-"] }

[[language]]
name = "go"
formatter = { command = "goimports" }
config = { goimports = true, gofumpt = true, staticcheck = true, analyses = { unusedparams = true, unreachable = true } }

[[language]]
name = "nix"
scope = "source.nix"
injection-regex = "nix"
file-types = ["nix"]
shebangs = []
roots = []
comment-token = "#"
language-server = { command = "nil" }
indent = { tab-width = 2, unit = "  " }
auto-format = true 

[[language]]
name = "markdown"
file-types = ["md", "eml"]
language-server = { command = "ltex-ls" }

[[language]]
name = "html"
file-types = ["html"]
auto-format = false
language-server = { command = "vscode-html-language-server", args = ["--add-flags", "--stdio"] }

[[language]]
name = "css"
file-types = ["css", "scss"]
language-server = { command = "vscode-css-language-server", args = ["--add-flags", "--stdio"] }

[[language]]
name = "javascript"
file-types = ["js"]
language-server = { command = "typescript-language-server", args = ["--stdio"] }

[[grammar]]
name = "nix"
source = { git = "https://github.com/nix-community/tree-sitter-nix", rev = "1b69cf1fa92366eefbe6863c184e5d2ece5f187d" }

